version: '3.9'
services:
  www:
    image: ghcr.io/fosten/farmos-mountain-site-3.x:${STACK_PARAM:-latest}
    networks:
      - traefik-public
    environment:
      TEST_DB_NAME: ${TEST_DB_NAME}
      TEST_DB_USER: ${TEST_DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - farmtest_default:/opt/drupal/web/sites/default
      - ${HOME}/keys/:/opt/drupal/keys
      - ${HOME}/farmtest_private/:${HOME}/farmtest_private/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == farmosapp
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.constraint-label=public
        # SERVICES: Main
        - traefik.http.services.farmtest.loadbalancer.server.port=80
        # MIDDLEWARES: farmtest-cors
        - traefik.http.middlewares.farmtest-cors.headers.accesscontrolallowmethods=*
        - traefik.http.middlewares.farmtest-cors.headers.accesscontrolallowheaders=*
        - traefik.http.middlewares.farmtest-cors.headers.accesscontrolalloworiginlist=${CORS_ALLOW_ORIGIN}
        - traefik.http.middlewares.farmtest-cors.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.farmtest-cors.headers.addvaryheader=true
        # MIDDLEWARES: farmtest-auth
        - traefik.http.middlewares.farmtest-auth.basicauth.users=admin:${TESTING_TRAEFIK_HASHED_PASSWORD}
        # MIDDLEWARES: farmtest-ipallowlist
        - traefik.http.middlewares.farmtest-ipallowlist.ipallowlist.sourcerange=${API_IP_ALLOWLIST}
        # MIDDLEWARES: farmtest-redirect-showcore
        - traefik.http.middlewares.farmtest-redirect-showcore.redirectregex.regex=^(https?://[^/]+)(\\?.*showcore.*)$$
        - traefik.http.middlewares.farmtest-redirect-showcore.redirectregex.replacement=$${1}/user/login$${2}
        - traefik.http.middlewares.farmtest-redirect-showcore.redirectregex.permanent=true
        # HOSTS: Main
        - traefik.http.routers.farmtest.rule=Host(`farmtest.lillymountain.com`)
        - traefik.http.routers.farmtest.entrypoints=https
        - traefik.http.routers.farmtest.tls=true
        - traefik.http.routers.farmtest.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmtest.service=farmtest
        - traefik.http.routers.farmtest.middlewares=farmtest-cors,farmtest-redirect-showcore
        # HOSTS: Showcore Login
        - traefik.http.routers.farmtest-showcore.rule=(Host(`farmtest.lillymountain.com`) && PathPrefix(`/user/login`) && Query(`showcore`))
        - traefik.http.routers.farmtest-showcore.entrypoints=https
        - traefik.http.routers.farmtest-showcore.tls=true
        - traefik.http.routers.farmtest-showcore.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmtest-showcore.service=farmtest
        - traefik.http.routers.farmtest-showcore.middlewares=farmtest-cors,farmtest-auth
        # HOSTS: API
        - traefik.http.routers.farmtest-api.rule=(Host(`farmtest.lillymountain.com`) && (PathPrefix(`/api/`) || PathPrefix(`/oauth/`)))
        - traefik.http.routers.farmtest-api.entrypoints=https
        - traefik.http.routers.farmtest-api.tls=true
        - traefik.http.routers.farmtest-api.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmtest-api.service=farmtest
        - traefik.http.routers.farmtest-api.middlewares=farmtest-cors,farmtest-ipallowlist

volumes:
  farmtest_default: {}

networks:
  traefik-public:
    external: true
