version: '3.8'
services:
  db:
    image: postgres:15
    networks:
      - farmos-private-release
    volumes:
      - './release-db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  www:
    depends_on:
      - db
    image: ghcr.io/fosten/farmos-mountain-site-3.4.3:${STACK_PARAM:-latest}
    networks:
      - farmos-private-release
    volumes:
      - './release-www:/opt/drupal/web/sites/default'
    ports:
      - '80:80'
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1
      # Enable these for PHPStorm:
      XDEBUG_SESSION: PHPSTORM
      PHP_IDE_CONFIG: serverName=localhost

networks:
  farmos-private-release:
    driver: bridge
    name: farmos-private-release
