version: '3.9'
services:
  www:
    image: ghcr.io/fosten/farmos-mountain-site-3.4.5:${STACK_PARAM:-latest}
    networks:
      - traefik-public
    environment:
      PROD_DB_NAME: ${PROD_DB_NAME}
      PROD_DB_USER: ${PROD_DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - farmrelease_default:/opt/drupal/web/sites/default
      - ${HOME}/keys/:/opt/drupal/keys
      - ${HOME}/farmos_private/:${HOME}/farmos_private/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == farmosapp
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.constraint-label=public
        # SERVICES: Main
        - traefik.http.services.farmos.loadbalancer.server.port=80
        # MIDDLEWARES: farmos-cors
        - traefik.http.middlewares.farmos-cors.headers.accesscontrolallowmethods=*
        - traefik.http.middlewares.farmos-cors.headers.accesscontrolallowheaders=*
        - traefik.http.middlewares.farmos-cors.headers.accesscontrolalloworiginlist=${CORS_ALLOW_ORIGIN}
        - traefik.http.middlewares.farmos-cors.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.farmos-cors.headers.addvaryheader=true
        # MIDDLEWARES: farmos-auth
        - traefik.http.middlewares.farmos-auth.basicauth.users=admin:${PROD_TRAEFIK_HASHED_PASSWORD}
        # MIDDLEWARES: farmos-ipallowlist
        - traefik.http.middlewares.farmos-ipallowlist.ipallowlist.sourcerange=${API_IP_ALLOWLIST}
        # MIDDLEWARES: farmos-redirect-showcore
        - traefik.http.middlewares.farmos-redirect-showcore.redirectregex.regex=^(https?://[^/]+)(\\?.*showcore.*)$$
        - traefik.http.middlewares.farmos-redirect-showcore.redirectregex.replacement=$${1}/user/login$${2}
        - traefik.http.middlewares.farmos-redirect-showcore.redirectregex.permanent=true
        # HOSTS: Main
        - traefik.http.routers.farmos.rule=Host(`farmos.lillymountain.com`)
        - traefik.http.routers.farmos.entrypoints=https
        - traefik.http.routers.farmos.tls=true
        - traefik.http.routers.farmos.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmos.service=farmos
        - traefik.http.routers.farmos.middlewares=farmos-cors,farmos-redirect-showcore
        # HOSTS: Showcore Login
        - traefik.http.routers.farmos-showcore.rule=(Host(`farmos.lillymountain.com`) && PathPrefix(`/user/login`) && Query(`showcore`))
        - traefik.http.routers.farmos-showcore.entrypoints=https
        - traefik.http.routers.farmos-showcore.tls=true
        - traefik.http.routers.farmos-showcore.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmos-showcore.service=farmos
        - traefik.http.routers.farmos-showcore.middlewares=farmos-cors,farmos-auth
        # HOSTS: API
        - traefik.http.routers.farmos-api.rule=(Host(`farmos.lillymountain.com`) && (PathPrefix(`/api/`) || PathPrefix(`/oauth/`)))
        - traefik.http.routers.farmos-api.entrypoints=https
        - traefik.http.routers.farmos-api.tls=true
        - traefik.http.routers.farmos-api.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmos-api.service=farmos
        - traefik.http.routers.farmos-api.middlewares=farmos-cors,farmos-ipallowlist

volumes:
  farmrelease_default: {}

networks:
  traefik-public:
    external: true
