version: '3.9'
services:
  www:
    image: ghcr.io/fosten/farmos-mountain-site-3.x-dev:${STACK_PARAM:-latest}
    networks:
      - traefik-public
    environment:
      DEV_DB_NAME: ${DEV_DB_NAME}
      DEV_DB_USER: ${DEV_DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - farmdev_default:/opt/drupal/web/sites/default
      - ${HOME}/keys/:/opt/drupal/keys
      - ${HOME}/farmdev_private/:${HOME}/farmdev_private/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == farmosapp
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.constraint-label=public
        # SERVICES: Main
        - traefik.http.services.farmdev.loadbalancer.server.port=80
        # MIDDLEWARES: farmdev-cors
        - traefik.http.middlewares.farmdev-cors.headers.accesscontrolallowmethods=*
        - traefik.http.middlewares.farmdev-cors.headers.accesscontrolallowheaders=*
        - traefik.http.middlewares.farmdev-cors.headers.accesscontrolalloworiginlist=${CORS_ALLOW_ORIGIN}
        - traefik.http.middlewares.farmdev-cors.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.farmdev-cors.headers.addvaryheader=true
        # MIDDLEWARES: farmdev-auth
        - traefik.http.middlewares.farmdev-auth.basicauth.users=admin:${DEV_TRAEFIK_HASHED_PASSWORD}
        # MIDDLEWARES: farmdev-ipallowlist
        - traefik.http.middlewares.farmdev-ipallowlist.ipallowlist.sourcerange=${API_IP_ALLOWLIST}
        # HOSTS: Main
        - traefik.http.routers.farmdev.rule=Host(`farmdev.lillymountain.com`)
        - traefik.http.routers.farmdev.entrypoints=https
        - traefik.http.routers.farmdev.tls=true
        - traefik.http.routers.farmdev.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmdev.service=farmdev
        - traefik.http.routers.farmdev.middlewares=farmdev-cors,farmdev-auth
        # HOSTS: API
        - traefik.http.routers.farmdev-api.rule=(Host(`farmdev.lillymountain.com`) && (PathPrefix(`/api/`) || PathPrefix(`/oauth/`)))
        - traefik.http.routers.farmdev-api.entrypoints=https
        - traefik.http.routers.farmdev-api.tls=true
        - traefik.http.routers.farmdev-api.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmdev-api.service=farmdev
        - traefik.http.routers.farmdev-api.middlewares=farmdev-cors,farmdev-ipallowlist
volumes:
  farmdev_default: {}

networks:
  traefik-public:
    external: true
