version: '3.9'
services:
  www:
    image: ghcr.io/fosten/farmos-mountain-site-3.x:${STACK_PARAM:-latest}
    networks:
      - traefik-public
    environment:
      TEST_DB_NAME: ${TEST_DB_NAME}
      TEST_DB_USER: ${TEST_DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - farmtest_default:/opt/drupal/web/sites/default
      - ${HOME}/keys/:/opt/drupal/keys
      - ${HOME}/farmtest_private/:${HOME}/farmtest_private/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == farmosapp
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.constraint-label=public
        # SERVICES: Main
        - traefik.http.services.farmos-testing.loadbalancer.server.port=80
        # MIDDLEWARES: Main
        - traefik.http.middlewares.cors-testing.headers.accesscontrolallowmethods=*
        - traefik.http.middlewares.cors-testing.headers.accesscontrolallowheaders=*
        - traefik.http.middlewares.cors-testing.headers.accesscontrolalloworiginlist=${CORS_ALLOW_ORIGIN}
        - traefik.http.middlewares.cors-testing.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.cors-testing.headers.addvaryheader=true
        ## farmOS Testing Instance Access Authentication
        ## Change the auth password here
        - traefik.http.middlewares.farmos-testing-auth.basicauth.users=admin:${TESTING_TRAEFIK_HASHED_PASSWORD}
        - traefik.http.middlewares.farmos-testing-ipallowlist.ipallowlist.sourcerange=${API_IP_ALLOWLIST}
        # HOSTS: Main
        - traefik.http.routers.farmos-testing.rule=Host(`farmtest.lillymountain.com`)
        - traefik.http.routers.farmos-testing.entrypoints=https
        - traefik.http.routers.farmos-testing.tls=true
        - traefik.http.routers.farmos-testing.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmos-testing.service=farmos-testing
        - traefik.http.routers.farmos-testing.middlewares=gzip,cors-testing,farmos-testing-auth
        # HOSTS: API
        - traefik.http.routers.farmos-testing-api.rule=(Host(`farmtest.lillymountain.com`) && (PathPrefix(`/api/`) || PathPrefix(`/oauth/`)))
        - traefik.http.routers.farmos-testing-api.entrypoints=https
        - traefik.http.routers.farmos-testing-api.tls=true
        - traefik.http.routers.farmos-testing-api.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmos-testing-api.service=farmos-testing
        - traefik.http.routers.farmos-testing-api.middlewares=gzip,cors-testing,farmos-testing-ipallowlist

volumes:
  farmtest_default: {}

networks:
  traefik-public:
    external: true
