version: '3.9'
services:
  www:
    image: ghcr.io/fosten/farmos-mountain-site-3.x-dev:${STACK_PARAM:-latest}
    networks:
      - traefik-public
    environment:
      DEV_DB_NAME: ${DEV_DB_NAME}
      DEV_DB_USER: ${DEV_DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - 83:80
    volumes:
      - farmdev_default:/opt/drupal/web/sites/default
      - ${HOME}/keys/:/opt/drupal/keys
      - ${HOME}/farmdev_private/:${HOME}/farmdev_private/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == farmosapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=public
        # SERVICES: Main
        - traefik.http.services.farmos-dev.loadbalancer.server.port=80
        # MIDDLEWARES: Main
        - traefik.http.middlewares.cors-dev.headers.accesscontrolallowmethods=*
        - traefik.http.middlewares.cors-dev.headers.accesscontrolallowheaders=*
        - traefik.http.middlewares.cors-dev.headers.accesscontrolalloworiginlist=https://plone.duckdns.org:5443
        - traefik.http.middlewares.cors-dev.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.cors-dev.headers.addvaryheader=true
        ## farmOS Development Instance Access Authentication
        ## Defaults to admin:admin
        - traefik.http.middlewares.farmos-dev-auth.basicauth.users=admin:$$apr1$$uZPT5Fgu$$AmlIdamxT5ipBvPlsdfD70
        - traefik.http.middlewares.farmos-dev-ipallowlist.ipallowlist.sourcerange=${API_IP_WHITELIST}
        # HOSTS: Main
        - traefik.http.routers.farmos-dev.rule=Host(`farmdev.lillymountain.com`)
        - traefik.http.routers.farmos-dev.entrypoints=websecure
        - traefik.http.routers.farmos-dev.tls=true
        - traefik.http.routers.farmos-dev.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmos-dev.service=farmos-dev
        - traefik.http.routers.farmos-dev.middlewares=gzip,cors-dev,farmos-dev-auth
        # HOSTS: API
        - traefik.http.routers.farmos-dev-api.rule=(Host(`farmdev.lillymountain.com`) && (PathPrefix(`/api/`) || PathPrefix(`/oauth/`)))
        - traefik.http.routers.farmos-dev-api.entrypoints=websecure
        - traefik.http.routers.farmos-dev-api.tls=true
        - traefik.http.routers.farmos-dev-api.tls.certresolver=mydnschallenge
        - traefik.http.routers.farmos-dev-api.service=farmos-dev
        - traefik.http.routers.farmos-dev-api.middlewares=gzip,cors-dev,farmos-dev-ipallowlist
volumes:
  farmdev_default: {}

networks:
  traefik-public:
    external: true
