name: Build farmOS Dev CI

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./farmOS

env:
  IMAGE_NAME_PREFIX: ghcr.io/fosten/farmos-mountain-site-3.x-dev
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME_PREFIX }}
          labels: |
            org.label-schema.docker.cmd=docker run -d -p 80:80 ${{ env.IMAGE_NAME_PREFIX }}:latest
          flavor:
            latest=false
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Login to Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          load: true
          context: farmOS/
          file: farmOS/Dockerfile.dev
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Start container
        run: docker run -d --name www ${{ env.IMAGE_NAME_PREFIX }}:latest
        
      - name: Run PHP CodeSniffer
        id: codesniffer
        run: docker exec -u www-data www phpcs /opt/drupal/web/modules/custom

      - name: Check PHP compatibility of contrib modules and themes (ignore warnings).
        id: phpcompatibility
        run: |
          docker exec -u www-data www phpcs --standard=PHPCompatibility --runtime-set testVersion 8.2- --warning-severity=0 /opt/drupal/web/modules
          docker exec -u www-data www phpcs --standard=PHPCompatibility --runtime-set testVersion 8.2- --warning-severity=0 /opt/drupal/web/themes

      - name: Run PHPStan
        id: phpstan
        run: docker exec -u www-data www phpstan analyze --memory-limit 1G /opt/drupal/web/profiles/farm

#      - name: Run PHPUnit
#        id: phpunit
#        run: docker exec -u www-data www phpunit --verbose /opt/drupal/web/profiles/farm

      - name: Report
        if: ${{ success() || failure() }}
        run: |
          echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
          echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| CodeSniffer | ${{ steps.codesniffer.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
          echo '| PHP compatibility | ${{ steps.phpcompatibility.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
          echo '| PHPStan | ${{ steps.phpstan.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_NAME_PREFIX }} --all-tags
